#nullable enable
using Content.Client.UserInterface.AdminMenu.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

namespace Content.Client.UserInterface.AdminMenu.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public partial class AdminTab : Control
    {
        public UICommandButton LogButton => LogButtonControl;
    }
}
