using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.AdminMenu.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public partial class LogWindow : SS14Window
    {
        public LogWindow()
        {
            RobustXamlLoader.Load(this);

            AllButton.OnPressed += AllButtonOnPressed;
            PointSelectorButton.OnPressed += PointSelectorButtonOnPressed;
            AreaSelectorButton.OnPressed += AreaSelectorButtonOnPressed;
        }

        private void AreaSelectorButtonOnPressed(BaseButton.ButtonEventArgs obj)
        {
            throw new System.NotImplementedException();
        }

        private void PointSelectorButtonOnPressed(BaseButton.ButtonEventArgs obj)
        {
            throw new System.NotImplementedException();
        }

        private void AllButtonOnPressed(BaseButton.ButtonEventArgs obj)
        {
            throw new System.NotImplementedException();
        }
    }
}
